[package]
name = "helloworld"
version = "0.1.0"
authors = ["Jin Hu <bixuehujin@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.50"
php-rs = { path = "../..", version = "0.1.0" }

[lib]
name = "helloworld"
crate-type = ["dylib"]
