[package]
name = "ivory-helloworld"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
ivory = { path = "../../ivory", version = "0.1.0" }

[lib]
name = "helloworld"
crate-type = ["dylib"]
