[package]
description = "Rust bindings for libphp"
name = "ivory-sys"
version = "7.3.3"
authors = ["Herman J. Radtke III <herman@hermanradtke.com>", "Heinz Gies <heinz@licenser.net>"]
links = "php7"
build = "build.rs"
license = "MIT"

[build-dependencies]
bindgen = "0.43"
cc = "1.0"
num_cpus="1.0"
